### ISSUE TITLE
Sidebar/header is smaller than the viewport

### ISSUE THREAD

**Issue by tylermumford** [tylermumford/tylermumford.com#1]
At first I thought this was just on one article page. Nope, it's the whole site.

![Screen Shot 2023-01-11 at 22 56 06](https://user-images.githubusercontent.com/531333/211988908-b2d7a7e8-9176-446e-803f-e50ca3888570.png)

**Comment by abitsalihu** [comment]
Hey @tylermumford, I would like to help with this issue. :)

**Comment by tylermumford** [comment]
> Hey @tylermumford, I would like to help with this issue. :)

Thank you for the kind offer, but... why? 🙃 This is my personal website, so I’m not expecting any outside contributions.

I'm not sure whether I want any contributors in this or not. I like being able to say that I put this site together myself.

**Comment by abitsalihu** [comment]
@tylermumford, well since I saw this issue open and no one assigned to it, my initial thought was that you were seeking outside help. Since this is your portfolio and you're going to showcase it as a project I think it would be best to work on it on your own.

 Good luck. :)
